### ISSUE TITLE
Add an option for Candlestick charts

### ISSUE THREAD

**Issue by sangelxyz** [vicanso/charts-rs#1]
Hi, is it possible to have candlestick charts added to charts.rs ?

**Comment by vicanso** [comment]
It's a bit complicated, and will be considered for support in future versions.

**Comment by vicanso** [comment]
@sangelxyz  Candlestick is supported now.

[Test demo](https://github.com/vicanso/charts-rs/blob/main/src/charts/candlestick_chart.rs#L329)
[Web demo](https://charts.npmtrend.com/) please select candlestick and click run button.

**Comment by sangelxyz** [comment]
Nice work, i'll try this on the weekend.
