### ISSUE TITLE
关于Echarts及其衍生项目的缺陷及吐槽/The defects of Echarts and it's derivatives

### ISSUE THREAD

**Issue by wangjiawen2013** [vicanso/charts-rs#10]
Echarts最初是由一家商业公司（也就是百度）开发的，带有浓重的商业风，特别适合用于商业报表。Echarts的开发人员现在不大愿意增加新的图表类型，他们认为现在的图表类型已经够多的了，增加类型会导致Echarts包太大，他们还要考虑新增的图表是否真的有用，只有频繁使用的他们才考虑增加（ https://github.com/apache/echarts/issues/11820#issuecomment-580996862 ）。比如常用的violinplot，errorbar plot等seaborn/matplotlib/ggplot支持的图Echarts都不支持，而plotly就支持这些（https://plotly.com/python/violin/）。

很多商业项目要用到各种图形库，但很多学术项目也会用到。科技类文章上要用到大量的图形，而Echarts的科技作图能力极差，说简单点就是Echarts的开发压根就没有考虑到科技作图的问题，也许他们当中都是公司的开发人员，没有各大高校和研究所的人，所以才压根儿意识不到这个问题，才会说出“要考虑violinplot，errorbar plot”是否有用的话。这些图形都是入门级的常见图形，在各种科技论文中已经烂大街了，Echarts团队还看不到这些事情。

许多Echarts的衍生项目，比如rust阵营中的charming，plotters(这个不是echarts的衍生）等各项目现在都是半死不活的状态，即使这些项目一直在维护也很难火起来，因为Echarts缺的东西他们也都缺少，没有什么特色。

相比之下Vega-Altair就平衡了许多，兼顾了商业和学术，而且它使用的数据结构是表格，这一点特别方便。但rust中没有vega-altair。

所以我觉得chart-rs可以吸收echarts和vega-altair的优点，添加一些常见的科技类图形且支持使用表格数据（比如与rust polars兼容）。否则即使做得和Echarts一样好也只能打50分，还是会重蹈charming和plotters的覆辙，这样chart-rs很有可能大火。Rust中统计学和统计作图都很弱，如果能有一些包出现，肯定会有很多人使用的，这目前几乎是一片荒地。

我们是做生命科学领域大数据处理的，以应用为主，缺乏开发能力。但我们也在学习，如果学会了如何开发图形库，一定会为此项目做出贡献的，也希望开发chart-js的大神能教教我们或者给我们一些开发图形库的基础知识资料。我们也认为Rust会是未来的发展方向，目前我们领域有一些比较著名的人物在推动这个事情了。

**Comment by wangjiawen2013** [comment]
https://github.com/yuankunzhang/charming/issues/42

**Comment by wangjiawen2013** [comment]
plotters and chart-js

https://github.com/plotters-rs/plotters/issues/546

**Comment by vicanso** [comment]
因为各种复杂的图表比较麻烦，后续尽量支持更多的种类。在此，谢谢对charts-rs的支持

**Comment by franksayyes** [comment]
复议，希望有小提琴图

**Comment by Kuroshimacat** [comment]
其实你们可以试试Plooters写一个的。
