### ISSUE TITLE
Project language from Chinese to English

### ISSUE THREAD

**Issue by wangjiawen2013** [vicanso/charts-rs#11]
Hi Xie,

It's better to switch working language and the code annotations to English in order to make chart-rs more popular and get more contribution from communities. There are lots of open source communities who are very professional. If so, chart-js can be improved greatly and avoid repeating the track of Echarts. The huge amount of Chinese issues on Echarts github are impeding communications with foreigners.

**Comment by wangjiawen2013** [comment]
![image](https://github.com/vicanso/charts-rs/assets/29703450/7332c8f8-5814-4a61-879f-6fd424901bdd)

**Comment by vicanso** [comment]
I will translate the comment later.

**Comment by ArmoredPony** [comment]
the demo page default language should be probably switched to english too
