### ISSUE TITLE
如何自定义Y轴最大值

### ISSUE THREAD

**Issue by scwcd** [vicanso/charts-rs#14]
![1](https://github.com/vicanso/charts-rs/assets/8776376/6bc9e804-5485-42a5-baff-5bd0b5a174e2)
曲线图上部有很多空白区域，如何设置Y轴最大值为800？

**Comment by vicanso** [comment]
指定Y轴的相关属性即可，如

```json
"y_axis_configs": [
    {
        "y_axis_split_number": 6,
        "axis_max": 800
    }
  ],
```

**Comment by scwcd** [comment]
问题已解决，谢谢！

**Comment by vicanso** [comment]
新版本调整了一下计算Y轴最大值的逻辑，可以尝试一下。

**Comment by vicanso** [comment]
逻辑的问题，当时想着尽可能Y轴是整数，忘记了统计数据也可能是很小的，后续版本优化。

**Comment by vicanso** [comment]
@scwcd  新版本是否还有问题？

**Comment by scwcd** [comment]
> @scwcd 新版本是否还有问题？

测试了0.3.11版，Y轴动态效果挺好。
![line](https://github.com/vicanso/charts-rs/assets/8776376/3def3f66-db89-4bc9-9378-7da920f9f65e)

但发现X轴最末端显示不完整，希望能够优化一下，谢谢！

**Comment by vicanso** [comment]
因为图表的点不够每一个块平分，由图可看出最后一块的点少一些，因此X轴最末端才未展示，如果可以则控制图中的数据，刚好可平分即可。
