### ISSUE TITLE
How to invert y axis and change bounds

### ISSUE THREAD

**Issue by AlexSCFraser** [vicanso/charts-rs#15]
Hi, 

I'm looking for a good library to make a plot of rankings over time that gets rendered out as both PNG and SVG for webpages/caching, etc. Tried several other Rust libs for graphing already and most of them are giving very ugly results. I like the output of charts-rs a lot, but I'm struggling to get the y-axis orientation and bounds correct.

My code looks like this

```
    let mut line_chart = LineChart::new_with_theme(
        vec![
            ("Rank", ranks).into(),
        ],
        dates,
        THEME_GRAFANA
    );
    line_chart.title_text = "Rank".to_string();
    line_chart.sub_title_text = format!("@{}", "username".to_string());
    line_chart.legend_margin = Some(Box {
        top: 50.0,
        bottom: 10.0,
        ..Default::default()
    });
    line_chart.width = 600.0;
    line_chart.height = 600.0;
    line_chart.series_list[0].label_show = true;
    line_chart.series_smooth = true;
    line_chart.y_axis_configs[0].axis_min = max_rank;
    line_chart.y_axis_configs[0].axis_max = min_rank;
    println!("{}", line_chart.svg().unwrap());
    write(output_path, line_chart.svg().unwrap())?;
```
![rank_plot](https://github.com/vicanso/charts-rs/assets/79180900/baef2c14-9292-4c71-ac50-15b113d57c5d)

The problem is that since it's rankings, lower is better and I want to invert the y-axis for the biggest number of the bound is at the bottom and the smallest number is at the top. Additionally, the bounds aren't being changed when I set axis_min and axis_max. I tried putting the max_rank as axis_min bound and min_rank as the axis_max, since that's how other graphing libraries sometimes invert the y-axis bounds, but it doesn't narrow the bound either way and doesn't invert.   I've tried the from_json method as well, from this generated json:

```
{
            "width": 600,
            "height": 600,
            "title_text": "Rank",
            "theme": "grafana",
            "sub_title_text": "@username",
            "legend_margin": {
                "left": 5,
                "right": 5,
                "top": 50,
                "bottom": 10
            },
            "series_list": [
                {
                    "name": "Rank",
                    "label_show": true,
                    "smooth": true,
                    "data": [980.0, 973.0, 971.0, 947.0, 908.0, 878.0, 786.0]
                }
            ],
            "series_smooth": true,
            "x_axis_data": ["05-26", "05-27", "05-28", "05-29", "05-30", "05-31", "06-01"],
            "y_axis_configs": [
                {
                    "axis_min": 980,
                    "axis_max": 786
                }
            ]
        }
```
I love the way the graphs look and this package is easy to use, I just need to get the y axis bounds changed and inverted, but I can't find anything in the docs to help with this.

**Comment by vicanso** [comment]
You can set min and max like this:

```json
 "y_axis_configs": [
                {
                    "axis_min": 786,
                    "axis_max": 980
                }
            ]
```
Invert y axis is not supported now.

**Comment by vicanso** [comment]
Can you provide an example or screenshot of another project? I didn't find any example in echarts.
