### ISSUE TITLE
找不到svg_to_png

### ISSUE THREAD

**Issue by datenxs** [vicanso/charts-rs#16]
按照您所提供的例子，发现找不到“svg_to_png”
![微信截图_20240616220214](https://github.com/vicanso/charts-rs/assets/172975179/bd969b10-b5a9-47cf-9fc4-c63c1763bb85)

**Comment by datenxs** [comment]
已解决，在Cargo.toml中
[dependencies]
charts-rs = { version = "0.3.10", features = ["image-encoder"] }
不过，png的路径要怎么指定呢？

**Comment by vicanso** [comment]
返回的是字节，需要自己保存了文件
Sent from my iPhone

On Jun 17, 2024, at 00:00, datenxs ***@***.***> wrote:

﻿

已解决，在Cargo.toml中
[dependencies]
charts-rs = { version = "0.3.10", features = ["image-encoder"] }
不过，png的路径要怎么指定呢？
