### ISSUE TITLE
evcxr jupyter

### ISSUE THREAD

**Issue by wangjiawen2013** [vicanso/charts-rs#18]
你好，
chart-rs 现在支持在 evcxr jupyter notebook 中使用吗？这样会很方便，尤其是在数据探索时，这时候还尚不清楚数据是什么样子以及该用什么图形表示。

**Comment by vicanso** [comment]
很抱歉，不支持

**Comment by wangjiawen2013** [comment]
近期有支持evcxr_jupyter的打算吗？

**Comment by vicanso** [comment]
暂时没有计划

**Comment by wangjiawen2013** [comment]
我刚为 plotpy 实现了 jupyter 在线展示的功能，如果以后需要的话可以参考一下：
https://github.com/cpmech/plotpy/pulls
