### ISSUE TITLE
水平柱状图数值显示不完整

### ISSUE THREAD

**Issue by scwcd** [vicanso/charts-rs#20]
![2024-08-07_171833](https://github.com/user-attachments/assets/a6d2e414-54a8-4398-ae41-ade5d5eda460)

**Comment by vicanso** [comment]
可设置margin right为更大的值试试。如:

```json
"margin": {
    "left": 5,
    "top": 5,
    "right": 50,
    "bottom": 5
  }
```

**Comment by scwcd** [comment]
可以了，谢谢！
