### ISSUE TITLE
Feature Request: Scatter Plot with Histogram

### ISSUE THREAD

**Issue by humphreylee** [vicanso/charts-rs#24]
Could you please consider adding scatter with marginal histogram on the sides like [this](https://au.mathworks.com/help/examples/stats/win64/CustomizethePlotDisplayExample_01.png), [this](https://s3.stackabuse.com/media/articles/matplotlib-scatter-plot-with-distribution-plots-histograms-jointplot-3.png) or [this](https://media.geeksforgeeks.org/wp-content/uploads/20201207115218/jointplot2-298x300.png)? Thanks.

**Comment by vicanso** [comment]
Have you ever tried using [multi charts](https://github.com/vicanso/charts-rs/blob/main/examples/multi_chart/main.rs).

**Comment by humphreylee** [comment]
I'm not sure if they are the same. The histogram appears to be "marginal" in comparison to the scatter plot. It needs to be "integrated," meaning it should directly relate to the scatter plot itself.
