### ISSUE TITLE
Document "image" feature flag, svg_to_png()

### ISSUE THREAD

**Issue by softmoth** [vicanso/charts-rs#3]
There is no documentation to say what the "image" feature provides. Also, when [searching the online documentation for "svg_to_png"](https://docs.rs/charts-rs/0.1.45/charts_rs/all.html?search=svg_to_png), it returns nothing.

The function is used in the examples, but it should also be in the documentation.

**Comment by vicanso** [comment]
I will fix it next version.

**Comment by softmoth** [comment]
Thank you

**Comment by datenxs** [comment]
[dependencies]
charts-rs = { version = "0.3.10", features = ["image-encoder"] }
should be added in Cargo.toml.

**Comment by datenxs** [comment]
In your Example of New from option, svg_to_png should be added as:

use charts_rs::{
    BarChart, Box, SeriesCategory, THEME_GRAFANA, svg_to_png
};
