### ISSUE TITLE
rust charming library

### ISSUE THREAD

**Issue by wangjiawen2013** [vicanso/charts-rs#8]
你好，
这个包和新出的charming有关系吗？charming (https://github.com/yuankunzhang/charming) 也是rust下的一个绘图包，也是源自于Echarts.

**Comment by vicanso** [comment]
没有关系的，charts-rs主要是我为了学习rust写在。`charming`是引入了echarts，通过deno_core来运行对应的js(没有深入研究也可能理解上有误），而charts-rs仅是参考echarts的ui，并没有使用到其代码，是纯rust的实现。

**Comment by wangjiawen2013** [comment]
你是从事什么工作的？有时间一直维护这个项目吗？Rust下面一直缺乏一个好用的作图库，charming算是不错的一个，但作者已经两个月不回答issue了。我学习过使用rust下的plotters， plotly还有charming，花费了我许多时间，但这些项目如果作者不继续开发的话肯定就都废掉了，虽说在学习使用这些作图库的过程中我也学到了不少关于rust的知识，但项目废掉还是让我觉得对不起付出的时间。如果你能一直维护charts-rs就再好不过了，我可以迁移到charts-rs上面来

**Comment by vicanso** [comment]
@wangjiawen2013 很高兴你考虑使用charts-rs，针对你上面的疑问：

- 只是一名普通的程序员
- 维护这个项目的时间是有的（非工作时间），最近这么多年一直都有维护自己的开源项目（均非工作需求），当然也都只是自己的作品，主要是熟悉各种的开发技术以及保持对编码的爱好
- 至于迁移至charts-rs，如果担心学习成本问题，建议直接尝试使用web的形式迁移部分需求，直接使用json的形式来生成图表，可先尝试一下：https://charts.npmtrend.com/，也提供了已编译好的镜像可直接部署

诚实的总结一下：charts-rs的项目是我为了学习rust而编写的，只要有问题都会及时回复，如果是bug那是会及时修复的，feature那可能要我评估后再决定。我开源了很多项目，基本都将自己的业余时间用于写代码，虽然都不火，但是rust是我以后的方向，所以最少几年内都可不用担心。

**Comment by wangjiawen2013** [comment]
能否留个邮箱？

**Comment by vicanso** [comment]
如果有问题可以直接在issue中提问的，会及时处理的，是有啥觉得需要邮件沟通么？

**Comment by wangjiawen2013** [comment]
我在一家商业公司从事大数据处理工作，目前正在建立在线大数据分析平台，不过我们这边没有相应专业的人，都是专业不对口的前后端开发人员。有时候我们问的一些问题可能会涉及到公司的数据和代码，到时候希望能通过邮件来发送。当然，绝大部分问题都是会在github上沟通的，只有极少数（理论上）觉得不便公开的信息才会以邮件形式进行沟通。

**Comment by vicanso** [comment]
那你可以发送至 tree.xie@outlook.com

**Comment by wangjiawen2013** [comment]
谢谢，我记下了，如果不想暴露联系方式现在可以把邮箱地址删了
