### ISSUE TITLE
中文渲染位置是否可以优化

### ISSUE THREAD

**Issue by lampofaladdin** [vicanso/charts-rs#9]
![image](https://github.com/vicanso/charts-rs/assets/26974584/5b7529e8-511f-4ec4-9fbb-83beceeaeafe)

大概是上图的样子

**Comment by vicanso** [comment]
默认的英文字体并不支持中文，因此会导致计算有误，选择一下字体即可以。
<img width="782" alt="image" src="https://github.com/vicanso/charts-rs/assets/437351/9bec712d-0d66-4b3b-b88d-4ca670d61e7d">

**Comment by lampofaladdin** [comment]
感谢大佬！
